### ISSUE TITLE
RPC method call to query number of proofs being processed

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#10]
Accuracy of proof generation timing tests depends on the prover load. Equal blocks (in terms of circuit cost) will differ in terms of proof generation duration, when different numbers of proofs are being queued/processed. Could we possibly add an rpc method call to audit the number of pending/queued blocks?
@ed255 @pinkiebell

**Comment by pinkiebell** [comment]
Is this about the `proverd` or the `coordinator`?
I have something on a "unreleased" table that may be useful to you. It will return all tasks the prover knows about, along with it's result. Would that be sufficient?

**Comment by AronisAt79** [comment]
> Is this about the `proverd` or the `coordinator`? I have something on a "unreleased" table that may be useful to you. It will return all tasks the prover knows about, along with it's result. Would that be sufficient?

I guess, any component that holds this information and exposes an api to retrieve, will be fine. 
I only need to know the number of the pending ones, but yes, i believe this will do. i can filter based on the result field.

**Comment by pinkiebell** [comment]
pr: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/631/files#diff-6954b46379253f1cfd72d35fd5d1995407afc793a96ac2e1d4843fcea87968e4R45

already landed on zkevm-chain. You can use  `method: "info"` on the `proverd` to retrieve the tasks. The `status` endpoint may be also interesting to you.
