### ISSUE TITLE
Write solidity code to generate the Root Circuit public inputs as specified by the PublicInputs circuit

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-chain#12]
Depends on https://github.com/privacy-scaling-explorations/zkevm-chain/issues/13

Also verify the proof by calling halo2 verifier contract from L1 zkRollup contract. Depends on https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/665

The PublicInputs public inputs construction is defined here https://github.com/privacy-scaling-explorations/zkevm-specs/blob/08c6c30a7b53f83558a7ea7e50dc0e4d74fab0c8/src/zkevm_specs/public_inputs.py#L290 Where `public_data` comes from the L1 Tx calldata (an encoding needs to be defined), `rand_rpi` comes from hashing the `raw_public_inputs` array like shown in the diagram https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/public_inputs.md and `MAX_TXS` and `MAX_CALLDATA_BYTES` are constants defined during the circuit setup.

**Comment by pinkiebell** [comment]
I'm splitting the halo verifier part into a standalone issue
