### ISSUE TITLE
Write solidity code to compute part of the public inputs

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-chain#13]
- For each tx, calculate TxSignHash as defined in https://github.com/privacy-scaling-explorations/zkevm-specs/blob/08c6c30a7b53f83558a7ea7e50dc0e4d74fab0c8/src/zkevm_specs/tx.py#L327
- For each tx, calculate the gas cost from call data as defined in https://github.com/privacy-scaling-explorations/zkevm-specs/blob/08c6c30a7b53f83558a7ea7e50dc0e4d74fab0c8/src/zkevm_specs/evm/typing.py#L150
- Fox each tx, calculate the CallDataLength

**Comment by pinkiebell** [comment]
@ed255 Must `rand_rpi` the hash of the `raw_public_inputs` table or can it also be the hash of the witness data, i.e. prior building the public input witness.

**Comment by pinkiebell** [comment]
@ed255 Second question, the layout for the [public input circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/public_inputs.py#L192) differs from the [table assignment function](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/typing.py#L164)

Any recommendations? 🙂

**Comment by ed255** [comment]
> @ed255 Must `rand_rpi` the hash of the `raw_public_inputs` table or can it also be the hash of the witness data, i.e. prior building the public input witness?

The `rand_rpi` should be a hash that uses as input: the `{Block Header, Txs and Extra}` data AND a column polynomial commitment that comes from a circuit (this value will be given by the prover).  The spec proposes to hash the `{Block Header, Txs and Extra}` by arranging it as the array `raw_public_inputs`.  But as long as a modification in any field inside `{Block Header, Txs and Extra}` leads to a change in the `rand_rpi` value; it should be fine!

The main point is that once the `rand_rpi` is calculated, the prover should not be able to change any value in `{Block Header, Txs and Extra}` or in the witness values of the `raw_public_inputs` in the PublicInputs circuit (that's why we feed it's commitment to the hash).  See this diagram for reference https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/public_inputs.rev1.png

I'm not sure what you mean by hashing the witness data.  If you're referring to the entire witness data of the PublicInputs circuits: this is not possible because `rand_rpi` is part of the witness data, so there's a circular dependency.

Does this answer your question?

> @ed255 Second question, the layout for the [public input circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/public_inputs.py#L192) differs from the [table assignment function](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/typing.py#L164)
> 
> Any recommendations? slightly_smiling_face

Yeah, sorry about that :sweat_smile: The correct one should be https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/typing.py#L164 that is:
- No GasTipCap
- No GasTipCap
- Yes CallDataLength
- Yes CallDataGasCost

**Comment by pinkiebell** [comment]
> > @ed255 Must `rand_rpi` the hash of the `raw_public_inputs` table or can it also be the hash of the witness data, i.e. prior building the public input witness?
> 
> The `rand_rpi` should be a hash that uses as input: the `{Block Header, Txs and Extra}` data AND a column polynomial commitment that comes from a circuit (this value will be given by the prover). The spec proposes to hash the `{Block Header, Txs and Extra}` by arranging it as the array `raw_public_inputs`. But as long as a modification in any field inside `{Block Header, Txs and Extra}` leads to a change in the `rand_rpi` value; it should be fine!
> 
> The main point is that once the `rand_rpi` is calculated, the prover should not be able to change any value in `{Block Header, Txs and Extra}` or in the witness values of the `raw_public_inputs` in the PublicInputs circuit (that's why we feed it's commitment to the hash). See this diagram for reference https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/public_inputs.rev1.png
> 
> I'm not sure what you mean by hashing the witness data. If you're referring to the entire witness data of the PublicInputs circuits: this is not possible because `rand_rpi` is part of the witness data, so there's a circular dependency.

I meant the raw-raw data before building the `raw_public_inputs` that contain all the necessary information for this process 

> Does this answer your question?

Yes. 

> 
> > @ed255 Second question, the layout for the [public input circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/public_inputs.py#L192) differs from the [table assignment function](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/typing.py#L164)
> > Any recommendations? slightly_smiling_face
> 
> Yeah, sorry about that 😅 The correct one should be https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/typing.py#L164 that is:
> 
> * No GasTipCap
> * No GasTipCap
> * Yes CallDataLength
> * Yes CallDataGasCost

👍

**Comment by pinkiebell** [comment]
fixed via c7271d6d0fd0cd47d904e52422ed723730cbce90
