### ISSUE TITLE
Calculate the OPCODE circuit cost for the State Circuit

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-chain#15]
Calculate the circuit height that each OPCODE will require from the State Circuit.

Write a script that goes through all the OPCODEs and how many rows of the State Circuit the OPCODE requires.

**Comment by pinkiebell** [comment]
related: https://github.com/pinkiebell/zkevm-circuits/blob/9d3d7e6f03b76477381ea3265165c703e44e1060/prover/tests/autogen.rs#L223

**Comment by ed255** [comment]
I already have the table generated from this test function https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/80a2327189878b7ba544de8ae7c7cba3c7005a1c/zkevm-circuits/src/state_circuit.rs#L393 for which I'll make a PR later (I found a bug that I need to fix first).  Here are the results:


| state          | opcode         | h   | g     | h/g    |
| -------------- | -------------- | --- | ----- | ------ |
| STOP           | STOP           | 2   | 0     | inf    |
| ADD_SUB        | ADD            | 3   | 3     | 1.000  |
| ADD_SUB        | SUB            | 3   | 3     | 1.000  |
| MUL_DIV_MOD    | MUL            | 3   | 5     | 0.600  |
| MUL_DIV_MOD    | DIV            | 3   | 5     | 0.600  |
| MUL_DIV_MOD    | MOD            | 3   | 5     | 0.600  |
| SDIV_SMOD      | SDIV           | 3   | 5     | 0.600  |
| SDIV_SMOD      | SMOD           | 3   | 5     | 0.600  |
| ADDMOD         | ADDMOD         | 4   | 8     | 0.500  |
| MULMOD         | MULMOD         | 4   | 8     | 0.500  |
| EXP            | EXP            | 3   | 60    | 0.050  |
| SIGNEXTEND     | SIGNEXTEND     | 3   | 5     | 0.600  |
| CMP            | LT             | 3   | 3     | 1.000  |
| CMP            | GT             | 3   | 3     | 1.000  |
| CMP            | EQ             | 3   | 3     | 1.000  |
| SCMP           | SLT            | 3   | 3     | 1.000  |
| SCMP           | SGT            | 3   | 3     | 1.000  |
| ISZERO         | ISZERO         | 2   | 3     | 0.667  |
| BITWISE        | AND            | 3   | 3     | 1.000  |
| BITWISE        | OR             | 3   | 3     | 1.000  |
| BITWISE        | XOR            | 3   | 3     | 1.000  |
| NOT            | NOT            | 2   | 3     | 0.667  |
| BYTE           | BYTE           | 3   | 3     | 1.000  |
| SHL            | SHL            | 3   | 3     | 1.000  |
| SHR            | SHR            | 3   | 3     | 1.000  |
| SAR            | SAR            | 3   | 3     | 1.000  |
| SHA3           | SHA3           | 67  | 42    | 1.595  |
| ADDRESS        | ADDRESS        | 2   | 2     | 1.000  |
| BALANCE        | BALANCE        | 3   | 100   | 0.030  |
| ORIGIN         | ORIGIN         | 2   | 2     | 1.000  |
| CALLER         | CALLER         | 2   | 2     | 1.000  |
| CALLVALUE      | CALLVALUE      | 2   | 2     | 1.000  |
| CALLDATALOAD   | CALLDATALOAD   | 4   | 3     | 1.333  |
| CALLDATASIZE   | CALLDATASIZE   | 2   | 2     | 1.000  |
| CALLDATACOPY   | CALLDATACOPY   | 53  | 9     | 5.889  |
| CODESIZE       | CODESIZE       | 1   | 2     | 0.500  |
| CODECOPY       | CODECOPY       | 51  | 9     | 5.667  |
| GASPRICE       | GASPRICE       | 2   | 2     | 1.000  |
| EXTCODESIZE    | EXTCODESIZE    | 3   | 100   | 0.030  |
| EXTCODECOPY    | EXTCODECOPY    | 5   | 103   | 0.049  |
| RETURNDATASIZE | RETURNDATASIZE | 1   | 2     | 0.500  |
| RETURNDATACOPY | RETURNDATACOPY | 3   | 9     | 0.333  |
| EXTCODEHASH    | EXTCODEHASH    | 9   | 100   | 0.090  |
| BLOCKHASH      | BLOCKHASH      | 2   | 20    | 0.100  |
| BLOCKCTXU64    | TIMESTAMP      | 1   | 2     | 0.500  |
| BLOCKCTXU64    | NUMBER         | 1   | 2     | 0.500  |
| BLOCKCTXU64    | GASLIMIT       | 1   | 2     | 0.500  |
| BLOCKCTXU160   | COINBASE       | 1   | 2     | 0.500  |
| BLOCKCTXU256   | DIFFICULTY     | 1   | 2     | 0.500  |
| BLOCKCTXU256   | BASEFEE        | 1   | 2     | 0.500  |
| CHAINID        | CHAINID        | 1   | 2     | 0.500  |
| SELFBALANCE    | SELFBALANCE    | 3   | 5     | 0.600  |
| POP            | POP            | 1   | 2     | 0.500  |
| MEMORY         | MLOAD          | 34  | 3     | 11.333 |
| MEMORY         | MSTORE         | 34  | 3     | 11.333 |
| MEMORY         | MSTORE8        | 3   | 3     | 1.000  |
| SLOAD          | SLOAD          | 8   | 2100  | 0.004  |
| SSTORE         | SSTORE         | 10  | 22100 | 0.000  |
| JUMP           | JUMP           | 3   | 8     | 0.375  |
| JUMPI          | JUMPI          | 3   | 10    | 0.300  |
| PC             | PC             | 1   | 2     | 0.500  |
| MSIZE          | MSIZE          | 1   | 2     | 0.500  |
| GAS            | GAS            | 1   | 2     | 0.500  |
| JUMPDEST       | JUMPDEST       | 0   | 1     | 0.000  |
| PUSH           | PUSH1          | 1   | 3     | 0.333  |
| PUSH           | PUSH2          | 1   | 3     | 0.333  |
| PUSH           | PUSH3          | 1   | 3     | 0.333  |
| PUSH           | PUSH4          | 1   | 3     | 0.333  |
| PUSH           | PUSH5          | 1   | 3     | 0.333  |
| PUSH           | PUSH6          | 1   | 3     | 0.333  |
| PUSH           | PUSH7          | 1   | 3     | 0.333  |
| PUSH           | PUSH8          | 1   | 3     | 0.333  |
| PUSH           | PUSH9          | 1   | 3     | 0.333  |
| PUSH           | PUSH10         | 1   | 3     | 0.333  |
| PUSH           | PUSH11         | 1   | 3     | 0.333  |
| PUSH           | PUSH12         | 1   | 3     | 0.333  |
| PUSH           | PUSH13         | 1   | 3     | 0.333  |
| PUSH           | PUSH14         | 1   | 3     | 0.333  |
| PUSH           | PUSH15         | 1   | 3     | 0.333  |
| PUSH           | PUSH16         | 1   | 3     | 0.333  |
| PUSH           | PUSH17         | 1   | 3     | 0.333  |
| PUSH           | PUSH18         | 1   | 3     | 0.333  |
| PUSH           | PUSH19         | 1   | 3     | 0.333  |
| PUSH           | PUSH20         | 1   | 3     | 0.333  |
| PUSH           | PUSH21         | 1   | 3     | 0.333  |
| PUSH           | PUSH22         | 1   | 3     | 0.333  |
| PUSH           | PUSH23         | 1   | 3     | 0.333  |
| PUSH           | PUSH24         | 1   | 3     | 0.333  |
| PUSH           | PUSH25         | 1   | 3     | 0.333  |
| PUSH           | PUSH26         | 1   | 3     | 0.333  |
| PUSH           | PUSH27         | 1   | 3     | 0.333  |
| PUSH           | PUSH28         | 1   | 3     | 0.333  |
| PUSH           | PUSH29         | 1   | 3     | 0.333  |
| PUSH           | PUSH30         | 1   | 3     | 0.333  |
| PUSH           | PUSH31         | 1   | 3     | 0.333  |
| PUSH           | PUSH32         | 1   | 3     | 0.333  |
| DUP            | DUP1           | 2   | 3     | 0.667  |
| DUP            | DUP2           | 2   | 3     | 0.667  |
| DUP            | DUP3           | 2   | 3     | 0.667  |
| DUP            | DUP4           | 2   | 3     | 0.667  |
| DUP            | DUP5           | 2   | 3     | 0.667  |
| DUP            | DUP6           | 2   | 3     | 0.667  |
| DUP            | DUP7           | 2   | 3     | 0.667  |
| DUP            | DUP8           | 2   | 3     | 0.667  |
| DUP            | DUP9           | 2   | 3     | 0.667  |
| DUP            | DUP10          | 3   | 3     | 1.000  |
| DUP            | DUP11          | 3   | 3     | 1.000  |
| DUP            | DUP12          | 3   | 3     | 1.000  |
| DUP            | DUP13          | 3   | 3     | 1.000  |
| DUP            | DUP14          | 3   | 3     | 1.000  |
| DUP            | DUP15          | 3   | 3     | 1.000  |
| DUP            | DUP16          | 3   | 3     | 1.000  |
| SWAP           | SWAP1          | 4   | 3     | 1.333  |
| SWAP           | SWAP2          | 4   | 3     | 1.333  |
| SWAP           | SWAP3          | 4   | 3     | 1.333  |
| SWAP           | SWAP4          | 4   | 3     | 1.333  |
| SWAP           | SWAP5          | 4   | 3     | 1.333  |
| SWAP           | SWAP6          | 4   | 3     | 1.333  |
| SWAP           | SWAP7          | 4   | 3     | 1.333  |
| SWAP           | SWAP8          | 4   | 3     | 1.333  |
| SWAP           | SWAP9          | 3   | 3     | 1.000  |
| SWAP           | SWAP10         | 3   | 3     | 1.000  |
| SWAP           | SWAP11         | 3   | 3     | 1.000  |
| SWAP           | SWAP12         | 3   | 3     | 1.000  |
| SWAP           | SWAP13         | 3   | 3     | 1.000  |
| SWAP           | SWAP14         | 3   | 3     | 1.000  |
| SWAP           | SWAP15         | 3   | 3     | 1.000  |
| SWAP           | SWAP16         | 3   | 3     | 1.000  |
| LOG            | LOG0           | 135 | 887   | 0.152  |
| LOG            | LOG1           | 137 | 1262  | 0.109  |
| LOG            | LOG2           | 139 | 1637  | 0.085  |
| LOG            | LOG3           | 141 | 2012  | 0.070  |
| LOG            | LOG4           | 143 | 2387  | 0.060  |
| CREATE         | CREATE         | 6   | 32000 | 0.000  |
| CALL           | CALL           | 44  | 14273 | 0.003  |
| CALLCODE       | CALLCODE       | 1   | 14273 | 0.000  |
| RETURN         | RETURN         | 0   | 0     | NaN    |
| DELEGATECALL   | DELEGATECALL   | 1   | 180   | 0.006  |
| CREATE2        | CREATE2        | 6   | 32012 | 0.000  |
| STATICCALL     | STATICCALL     | 1   | 180   | 0.006  |
| SELFDESTRUCT   | SELFDESTRUCT   | 3   | 5000  | 0.001  |
