### ISSUE TITLE
Create a smart contract with mstore/mload to implement worst case block for state circuit

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-chain#16]

**Comment by aguzmant103** [comment]
Edu mentioned that there is a smart contract that can be used as a base for this task

**Comment by pinkiebell** [comment]
Are `mload` / `mstore` the worst possible opcodes for the state circuit? I head about `SMOD/SDIV` being the worst cc @ed255

**Comment by AronisAt79** [comment]
> Are `mload` / `mstore` the worst possible opcodes for the state circuit? I heard about `SMOD/SDIV` being the worst cc @ed255

SDIV is the EVM circuit's most expensive op. While we yet have no detailed cost tables for state, Han and Edu have confirmed that for state we need to look at mload/mstore in order to implement the worst case block

**Comment by AronisAt79** [comment]
Hi, some results from circuit cost calculations according to https://github.com/privacy-scaling-explorations/zkevm-chain/issues/15

with the attached smart contract (MLOAD.zip), we achieve the following:
Transaction with ~79300 MLOADs >> TxGas ~ 278643 (block GasUsed ~ 300k and MLOAD gas is 237906). MLOAD accounts for 2696268 state circuit rows out of 2717897 (>99% of transaction circuit cost).
[MLOAD300kGAS.zip](https://github.com/privacy-scaling-explorations/zkevm-chain/files/9490739/MLOAD300kGAS.zip)
[MLOAD.zip](https://github.com/privacy-scaling-explorations/zkevm-chain/files/9490755/MLOAD.zip)

Attaching also Tx trace from said transaction. 

Will set the issue state to "In Review" in case we want to reconsider if further optimization is needed @ed255

**Comment by ed255** [comment]
> Hi, some results from circuit cost calculations according to #15
> 
> with the attached smart contract (MLOAD.zip), we achieve the following: Transaction with ~79300 MLOADs >> TxGas ~ 278643 (block GasUsed ~ 300k and MLOAD gas is 237906). MLOAD accounts for 2696268 state circuit rows out of 2717897 (>99% of transaction circuit cost). [MLOAD300kGAS.zip](https://github.com/privacy-scaling-explorations/zkevm-chain/files/9490739/MLOAD300kGAS.zip) [MLOAD.zip](https://github.com/privacy-scaling-explorations/zkevm-chain/files/9490755/MLOAD.zip)
> 
> Attaching also Tx trace from said transaction.
> 
> Will set the issue state to "In Review" in case we want to reconsider if further optimization is needed @ed255

The numbers and trace looks good!  I don't think it can be optimized further, as the body of the loop i just consecutive MLOADs :).

**Comment by pinkiebell** [comment]
fyi: the circuit generation code also includes a MLOAD test now. [Here](https://github.com/privacy-scaling-explorations/zkevm-chain/blob/fafeeb0bc934d40dd1c5c24dacd2fb695fdb3e7e/prover/tests/autogen.rs#L436)

**Comment by pinkiebell** [comment]
The autogen stuff to estimate the circuit size includes both `MLOAD` and `SMOD` contracts.
