### ISSUE TITLE
contracts/PatriciaValidator: split _validatePatriciaProof into dedicated functions

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-chain#20]
The goal of this change is that account proof and storage proofs can be separately verified.

Instead of verifying account and storage of the L1 bridge on L2 for each message, verify the account proof once and save the last known storage root of the L1 bridge account (on L2 bridge).

For each message delivery(on L2), only submit a storage proof and validate against that.

**Comment by leolara** [comment]
@pinkiebell do we still have to do this?

**Comment by pinkiebell** [comment]
Yes. That saves precious calldata space and we are bounded by it because of the low amount of gas available on l2
