### ISSUE TITLE
Estimate compute/memory requirements for prover in latest release

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#22]
We need to estimate the amount of RAM for the new prover operation. RAM requirements are now considerably increased due to integration of super-circuits and caching of proving-key.

**Comment by AronisAt79** [comment]
proof generation is currently failing:

https://github.com/privacy-scaling-explorations/zkevm-chain/issues/23

**Comment by aguzmant103** [comment]
Depending on https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/790

**Comment by AronisAt79** [comment]
@pinkiebell @barryWhiteHat @ed255 @leolara 
i attempted to prove a 300k gas block (optimized for evm worst case) just to get a sense of needed resources. Ram consumption peaked long before the constraint failure kicked in, so i guess this might be a safe figure for needed resources. So, the peak ram usage is close to a glorious 1.3TB. Overall duration until failure was ~6hrs.

**Comment by AronisAt79** [comment]
> @pinkiebell @barryWhiteHat @ed255 @leolara 

the duration i reported in previous comment might be exaggerated as the mock prover is invoked and this is factored-in, in total duration. Will update

**Comment by pinkiebell** [comment]
@AronisAt79 Is the 1.3TB figure virtual or physical used memory?

**Comment by AronisAt79** [comment]
Figures for latest release here: https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/790

**Comment by pinkiebell** [comment]
We have monitoring / workflows in place to track usage. But feel free to create a new issue with an actionable item for tracking prover resources.
