### ISSUE TITLE
Include a mock prover instance into zkevm-chain compose project

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#24]
Having a mock prover deployed along with the real prover replicas will help us debug proof errors similar to the one reported in #23.
In normal operation we can leave the mock prover out of the flow. When a proof_request fails, or when it fails with specific error indication(s), the coordinator would then refeed the failed proof_request to the mock element.

**Comment by pinkiebell** [comment]
My commit message referenced the wrong issue 🐒 .  Fixed via abede6a73a4f4cff554e94df262bbbc9804dac56
