### ISSUE TITLE
A question on public input data in InstanceVerifier.sol

### ISSUE THREAD

**Issue by smtmfft** [privacy-scaling-explorations/zkevm-chain#4]
https://github.com/privacy-scaling-explorations/zkevm-chain/blob/bbda13d13de3be7f02af28215760dfe7f10e1dcb/contracts/verifier/InstanceVerifier.sol#L9

Hi,
I saw here public input data is copied from bytes to a uint256 array, as circuit/pair are working on BN254. Are there some elems in that array out of the BN254 p_mod which is 254bit? If yes, will that be a problem??
Thanks!

BTW: I learned the public input data as byte array which is generated from block data by @pinkiebell commit:
https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/333929c9b79f332e9d7eafd664b88d5dabafe98b#diff-e66eea6b96b2b75a5cd8bee4fe4798f2fdf89b994e27c3860a507923f3044629R43

**Comment by pinkiebell** [comment]
I mainly did that to accommodate the cape contract setup. At the moment I assume that each individual element is padded to 32 bytes. Those public inputs should be the block & tx data so those values are the 'raw' values - not BN254. The conversion to circuit values must happen inside the contract.

**Comment by pinkiebell** [comment]
No advantages. I only used them as reference and didn't want to modify the contracts yet. In the future we will have to, though.
For example, we want to verify the block/transaction and do the poly setup ideally in 1 iteration instead of iterating over the large calldata multiple times.

**Comment by smtmfft** [comment]
Got it, thanks!
