### ISSUE TITLE
PatriciaValidator: implement non-inclusion for storage proof

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-chain#40]
The Patricia validator contract only supports validating storage proofs for non-zero values (valid leaves). However, the `dropMessage` method requires to proof that a storage value is zero (not in the storage tree). 

This can be a dedicated function instead of being merged in `_validatePatriciaProof` if that is easier to implement.

**Comment by leolara** [comment]
@pinkiebell do we still have to do this?

**Comment by pinkiebell** [comment]
Yes. It's required for `dropMessage` i.e proofing that a message was not relayed
