### ISSUE TITLE
Create EKS cluster

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#45]

**Comment by pinkiebell** [comment]
@AronisAt79 This and a few other related issues are marked as `Done` in the project board, can this be closed?

**Comment by AronisAt79** [comment]
> @AronisAt79 This and a few other related issues are marked as `Done` in the project board, can this be closed?

Yeap! We do have some housekeeping to do :)

**Comment by pinkiebell** [comment]
Might be worthwhile to adapt a workflow here: https://github.com/orgs/privacy-scaling-explorations/projects/3/workflows/query_matched_archive_project_item

That closes all issues if status = done. I have no permissions to add a new workflow tho
