### ISSUE TITLE
Investigate: How to automate converting docker-compose.yml to kubernetes manifests

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#51]
In order to efficiently maintain two parallel chain testing environments, we need to come up with a way to automate steps (as much as possible) of docker-compose conversion to kubernetes manifest. There are available tools like "kompose" but so far it does not look consistent mainly due to compose complexity.

**Comment by pinkiebell** [comment]
Do you know which feature or part of the docker-compose file is too complex for `kompose`?
Maybe we can find a way to workaround this issue.

**Comment by AronisAt79** [comment]
> Do you know which feature or part of the docker-compose file is too complex for `kompose`? Maybe we can find a way to workaround this issue.

on point!! Maybe, it should be more precise to say that kompose is good for basic compose projects, for example, persistent volumes is pretty standard compose feature, but one that kompose does not get along well with :). Lets see what @ntampakas will come up with. Our intention here is to reduce manual work to the minimum possible. If it turns out that we can do minor changes on our compose (without structural impact) to enable more seamless "k"onversion, i guess we can discuss later on.

**Comment by ntampakas** [comment]
It becomes too complex (and probably it doesn' t make sense to spend more time on this) to implement a fully automated translation from docker-compose file to k8s resources.
Therefore, i will create an implementation that needs in certain cases, user interaction.
