### ISSUE TITLE
Collect task information of prover

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-chain#52]
We did like to collect proof results to make testing the aggregation circuit easier (SuperCircuit proofs).
Collect all tasks via `info` rpc method of the prover after the end of the CI run and upload it somewhere.

**Comment by pinkiebell** [comment]
cc @AronisAt79 @ntampakas

**Comment by AronisAt79** [comment]
Hi @pinkiebell 
i am adding this one to the backlog to line up for implementation. But we cant produce actual results while proof generation is blocked due to the keccak lookup error.

**Comment by pinkiebell** [comment]
Supported via [the heavy workflow](https://github.com/privacy-scaling-explorations/zkevm-chain/actions/workflows/heavy_test.yml)
