### ISSUE TITLE
New Feature: Control prover behavior (see details in issue)

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#58]
This may (ideally) be provisioned : 
1. globally via the config method
2. per proof request via the proof method options

Default: Only a real prover is invoked, on error, real prover retries based on the "retry" (flag true/false). 
Custom:  Mock prover is directly invoked (helpful in case we need to run a tx that we know fails and want to skip the real prover steps). Select ad hoc with proof_request option (??)
Custom: Via  config,  enable/disable proof generation retries. retry flag in proof_request overrules this one
Custom: Via  config,  enable/disable mock prover in case of error.

**Comment by pinkiebell** [comment]
@AronisAt79 Do you still need a config option that controls the `retry` option of coordinator > proverd ?
Otherwise from that above, the issue seems covered.

**Comment by AronisAt79** [comment]
> @AronisAt79 Do you still need a config option that controls the `retry` option of coordinator > proverd ? Otherwise from that above, the issue seems covered.

Yes, it is covered. Totally forgot this was still open :)
