### ISSUE TITLE
New Feature: Cancel/Stop ongoing prover tasks

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#59]
While we can use the flush method on cached/pending/completed tasks, this seems to not work on ongoing jobs. It would be helpful to expand the flush capability to ongoing proof jobs as a means of canceling/stopping. To make more sense, we could use the flush -ongoing option with a blockNumber argument only

**Comment by AronisAt79** [comment]
@leolara @pinkiebell 

i just figured out that the current implementation is that if flush is requested, ongoing proofs are normally processed till completion but result is ignored. 

[2022-09-24T16:51:48Z INFO  prover::shared_state] task was already removed, ignoring result ProofRequestOptions {
        block: 10,
        rpc: "http://leader-testnet-geth:8545/",
        retry: true,
        param: "/testnet/",
    }

Is it easy/possible to actually cancel ongoing tasks? This would help a lot to clear used resources in order to do more accurate benchmarks.

**Comment by pinkiebell** [comment]
This needs research #43
