### ISSUE TITLE
Withdrawal is not working?

### ISSUE THREAD

**Issue by skardas** [privacy-scaling-explorations/zkevm-chain#6]
whenever i withdraw from zkEth to Etherum network, i get following error:

execution reverted: L2_BRG: bonderFee must meet minimum requirements

**Comment by skardas** [comment]
I think the problem is estimateGas doesnot work properly for L2:

react_devtools_backend.js:4026 hop: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":277,\"error\":{\"code\":3,\"message\":\"execution reverted: L2_BRG: bonderFee must meet minimum requirements\",\"data\":\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000304c325f4252473a20626f6e646572466565206d757374206d656574206d696e696d756d20726571756972656d656e747300000000000000000000000000000000\"}}\n","error":{"code":3,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000304c325f4252473a20626f6e646572466565206d757374206d656574206d696e696d756d20726571756972656d656e747300000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gas\":\"0x7a120\",\"value\":\"0xa\",\"from\":\"0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39\",\"to\":\"0x86ca30bef97fb651b8d866d45503684b90cb3312\",\"data\":\"0xeea0d7b200000000000000000000000000000000000000000000000000000000000000620000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062c4bab600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":277,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8000/rpc/l2"}, method="estimateGas", transaction={"from":"0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39","gasLimit":{"type":"BigNumber","hex":"0x07a120"},"to":"0x86cA30bEF97fB651b8d866D45503684b90cb3312","value":{"type":"BigNumber","hex":"0x0a"},"data":"0xeea0d7b200000000000000000000000000000000000000000000000000000000000000620000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062c4bab600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.1)
    at e.value (index.ts:225:28)
    at e.value (index.ts:237:20)
    at Fe (json-rpc-provider.ts:80:16)
    at n.<anonymous> (json-rpc-provider.ts:562:20)
    at d (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at s (24.167ee758.chunk.js:2:953929)

**Comment by pinkiebell** [comment]
I guess that the withdraw amount is probably too small

**Comment by skardas** [comment]
no, i try to send 10ETH. still get the following error.

![image](https://user-images.githubusercontent.com/19305096/176439525-10816fc8-9bf8-40cd-bbb0-35e07a976334.png)

**Comment by skardas** [comment]
> I guess that the withdraw amount is probably too small

no, i try to send 10ETH. still get the following error.


![image](https://user-images.githubusercontent.com/19305096/176439754-d6ceeb72-8040-4f74-b9b8-93a1e99dccc3.png)

**Comment by pinkiebell** [comment]
In that case it's a UI bug, because `value: 0xa` is def. not > 10 ETH 😄 . Maybe it has something todo with the large amount of eth on the L1 account.
Anyway, the only reason we integrated the hop bridge is for testing the Optimism bridge wrapper for the zkevm native bridge. That said, we don't integrate the hop bonder service and thus you will not receive ETH on L1  - it only tests our message relayer that commits this transfer from L2 > L1 and that function does no payouts. 

If you want to test L1>L2,L2>L1 messaging you can use [this](https://github.com/privacy-scaling-explorations/zkevm-chain/tree/master/docs#layer-2---bridge)
