### ISSUE TITLE
Document that lzma system library is required for development

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/zkevm-chain#60]
In Debian, installing liblzma-dev solves it

**Comment by JSnobody** [comment]
Hi, @leolara , How about Ubuntu?
I got: 
 "error: failed to run custom build command for `rust-lzma v0.5.1 "  in Ubuntu 18.04.
My steps:
./scrpts/test_prover.sh eth_transfer

I tried to install liblzma, but failed. Could you help me?
Thanks.

**Comment by JSnobody** [comment]
Sorry, I just tried to use "sudo apt-get install liblzma-dev" , it seemd ok...
