### ISSUE TITLE
Proof generation fails with thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#7]
During proof generation tests for MULMOD opcode, it appears that the operation fails consistently when the number of MULMOD executions exceeds ~600. 

 thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', /zkevm-circuits/zkevm-circuits/src/state_circuit.rs:204:38
[2022-07-02T08:35:00Z INFO  prover::shared_state] task_result: Err(
        "task 39 panicked",
    )
[2022-07-02T08:35:01Z INFO  prover::shared_state] completed: ProofRequest {
        block_num: 4,
        rpc_url: "http://leader-testnet-geth:8545/",
        result: Some(
            Err(
                "task 39 panicked",
            ),
        ),
    }

Here is the contract used to trigger the MULMOD operation:

  // SPDX-License-Identifier: MIT
  
  pragma solidity =0.8.13;
  
  contract Check2 {
      struct Input {
          uint256 x;
          uint256 y;
          uint256 m;
          uint256 l;
      }
  
      function checkMulMod(
          uint256 x,
          uint256 y,
          uint256 m
      ) public pure returns (uint256 r) {
          assembly {
              r := mulmod(x, y, m)
          }
      }
  
      function checkBatch(Input calldata io) external {
          for (uint256 i = 0; i < io.l; i++) {
              checkMulMod(io.x, io.y, io.m);
          }
      }
  }

**Comment by AronisAt79** [comment]
Same error on latest release


thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', /zkevm-circuits/zkevm-circuits/src/state_circuit.rs:177:38
[2022-07-04T20:52:17Z INFO  prover::shared_state] task_result: Err(
        "unknown panic",
    )
[2022-07-04T20:52:17Z INFO  prover::shared_state] completed: ProofRequest {
        options: ProofRequestOptions {
            block: 13,
            rpc: "http://leader-testnet-geth:8545/",
            retry: false,
            param: "/testnet/19.bin",
        },
        result: Some(
            Err(
                "unknown panic",
            ),
        ),
    }

**Comment by pinkiebell** [comment]
Probably due to [this](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2aa9875/prover/src/compute_proof.rs#L64)

@CPerezz Should we just increase it or making it more dynamic at runtime?

**Comment by CPerezz** [comment]
> Probably due to [this](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2aa9875/prover/src/compute_proof.rs#L64)
> 
> @CPerezz Should we just increase it or making it more dynamic at runtime?

I'm not sure this is the error TBH. I still need to check the trace (I've been busy with keccak). But an error for out_of_rows should be different.
What if you `unwrap` directly without adding any message? That should give us the exact line at which the code halts.

**Comment by pinkiebell** [comment]
I pushed a preliminary [update](https://github.com/pinkiebell/zkevm-circuits/compare/v2022-07-05...v2022-07-05-2) 
Let me know if the testflow works with this setup. We may want to be a bit smarter in the future about choosing n_rows tho^^

**Comment by AronisAt79** [comment]
Thanks @pinkiebell and @CPerezz for looking into the issue. I will retest and let you know.

**Comment by pinkiebell** [comment]
Great! I think you can close it and discuss the specifics of the solution in new pr or issue regarding the `N_ROWS` stuff.
