### ISSUE TITLE
Add a proof_request_option to control if mock_prover is engaged after proof generation fails

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-chain#80]
@leolara @pinkiebell 

Is it feasible to enhance the functionality added here 

https://github.com/privacy-scaling-explorations/zkevm-chain/commit/abede6a73a4f4cff554e94df262bbbc9804dac56

with a proof_request boolean option to enable/disable triggering of mock prover?

**Comment by AronisAt79** [comment]
Thanks @pinkiebell . Do you think we have capacity in this sprint to pick this one up? @leolara maybe?

**Comment by pinkiebell** [comment]
> Thanks @pinkiebell . Do you think we have capacity in this sprint to pick this one up? @leolara maybe?

Yes. I can pick this up soon 👌

**Comment by leolara** [comment]
Ok, let me know if you want me to do it in case you do not have time.

**Comment by leolara** [comment]
@AronisAt79 @pinkiebell I am looking at this issue and the PR and I have the impression that there is a confusion about what is the goal of this?

@AronisAt79 are you sure you are pointing to the right commit?

Don't you mean to extend this method https://github.com/privacy-scaling-explorations/zkevm-chain/blob/master/coordinator/src/bin/coordinator.rs#L326-L339 to be able to change another flag? That is what I understood you said at Bogota.

**Comment by AronisAt79** [comment]
> @AronisAt79 @pinkiebell I am looking at this issue and the PR and I have the impression that there is a confusion about what is the goal of this?
> 
> @AronisAt79 are you sure you are pointing to the right commit?
> 
> Don't you mean to extend this method https://github.com/privacy-scaling-explorations/zkevm-chain/blob/master/coordinator/src/bin/coordinator.rs#L326-L339 to be able to change another flag? That is what I understood you said at Bogota.

Hi @leolara , no the one we discussed back in Bogota concerns the coordinator config. This one targets proof requests

**Comment by leolara** [comment]
ok, I got confused

**Comment by pinkiebell** [comment]
I think that it makes sense to add a config option to the coordinator too. As well as to support live config changes for the coordinator in the future.

**Comment by pinkiebell** [comment]
I updated #81 . Let me know if it helps 👌

**Comment by AronisAt79** [comment]
This is now covered by #81 . Closing
