### ISSUE TITLE
Warning during proof

### ISSUE THREAD

**Issue by ntampakas** [privacy-scaling-explorations/zkevm-chain#9]
I sent funds from L1->L2 and the following warning message appears during the proof calculation:

```
[2022-07-13T12:10:42Z INFO  prover::shared_state] pending: ProofRequest {
        options: ProofRequestOptions {
            block: 2,
            rpc: "http://leader-testnet-geth:8545/",
            retry: false,
            param: "/testnet/19.bin",
        },
        result: None,
    }
WARN: evaluate_h: lookups.len() (0) != pk.vk.cs.lookups.len() (49)

```
Not sure if you are aware of this, that` s why i created the issue.

Env:
k8s (with real prover) running current version of zkevm-chain.

**Comment by pinkiebell** [comment]
Yes, this is expected. We don't have any public inputs connected yet
